server:
  port: 8002

spring:
  application:
    name: cloud-pay-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:9000/eureka/,http://eureka-server1:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
